-- Add location_labels column to problems table
ALTER TABLE problems ADD COLUMN IF NOT EXISTS location_labels TEXT[];

-- Clear existing quant topic assignments and topics
DELETE FROM problem_quant_topics;
DELETE FROM quant_topics;

-- Reset sequence
ALTER SEQUENCE quant_topics_id_seq RESTART WITH 1;

-- Insert 93 new quant topics
INSERT INTO quant_topics (name) VALUES
('Induction'),
('Logical Reasoning'),
('Symmetry'),
('Series'),
('Pigeon Principle'),
('Problem Simplification'),
('Modular Arithmetic'),
('Proof by Contradiction'),
('Calculus Methods'),
('Vector Geometry'),
('Determinant and Rank'),
('Eigenvalues and Eigenvectors'),
('Positive Semi-Definiteness (PSD)'),
('Quadratic Forms'),
('QR Decompositions'),
('SVD Decomposition'),
('LU and Cholesky Decompositions'),
('Principle Component Analysis (PCA)'),
('Probability Modeling'),
('Counting'),
('Geometric Probability'),
('Combinatorial Probability'),
('Inclusion and Exclusion Principle'),
('Conditional Probability and Bayesian Law'),
('Expectation and Variance'),
('Covariance and Correlation'),
('Uniform Distribution'),
('Geometric Distribution'),
('Exponential Distribution'),
('Poisson Distribution'),
('(Multivariate) Gaussian Distributions'),
('Linearity of Expectations'),
('Order Statistics'),
('Max and Min'),
('Applications of Symmetry'),
('Markov Chain'),
('Martingale'),
('Random Walk'),
('Brownian Motion'),
('Stochastic Calculus'),
('Poisson Processes'),
('Dynamical Programming'),
('Coin Flipping'),
('Dice Rolling'),
('Game Theory'),
('Estimators'),
('Sampling Distribution'),
('Bias-Variance'),
('Likelihood'),
('Bayesian Inference'),
('Law of Large Numbers (LLN)'),
('Central Limit Theorem (CLT)'),
('Rejection Sampling'),
('Uniform Sampling'),
('Hypothesis Testing'),
('Linear Regression'),
('Ridge and Lasso Regression'),
('Logistic Regression'),
('Quantile Regression'),
('Maximum Likelihood Estimate (MLE)'),
('Time Series Analysis'),
('Monte Carlo'),
('Information Theory'),
('Games'),
('Randomization Strategy'),
('Bidding'),
('Optimization'),
('Numerical Methods'),
('Algorithms and Data Structures'),
('Arrays and Strings'),
('Two Pointers'),
('Sliding Window'),
('Hashing'),
('Linked Lists'),
('Stacks and Queues'),
('Trees and Graphs'),
('Heaps'),
('Greedy'),
('Binary Search'),
('Backtracking'),
('Dynamical Programming (Coding)'),
('Machine Learning'),
('Classification Algorithms'),
('Random Forest'),
('Data Science'),
('AI/LLM'),
('Finance'),
('Python'),
('C++'),
('Java'),
('Nontraditional'),
('Approximation'),
('Paradox');
